#!/bin/bash

# User stuff
PATH=$PATH:~/bin  # Add user binaries.

# === PYTHON === #
export WORKON_HOME=$HOME/.virtualenvs
PATH=~/.local/bin:$PATH  # Fix for pip on ubuntu, prioritizes local modules.

if hash pyenv 2>/dev/null; then
	eval "$(pyenv init -)"  # Initialize pyenv if it is installed
fi

# === GO === #
#if hash go 2>/dev/null; then
# TODO: Fix "exists" check.
export GO111MODULE=on
export GOPATH=~
PATH=$GOROOT/bin:$GOPATH/bin:$PATH  # Add go-related stuff to path
#fi

# === JS === #
if hash yarn 2>/dev/null; then
    PATH="$(yarn global bin):$PATH"  # Source yarn global path if yarn is installed.
fi

# === Rust === #
if [ -d "$HOME/.cargo" ]; then
	export PATH="$HOME/.cargo/bin:$PATH"

	if [ -d "$HOME/.cargo/env" ]; then
		source $HOME/.cargo/env
	fi
fi

# === GCLOUD == #
# Initialize Google cloud zsh completion
if [ -f ${HOME}/.gcloud-sdk/path.zsh.inc ]; then . ${HOME}/.gcloud-sdk/path.zsh.inc; fi
if [ -f ${HOME}/.gcloud-sdk/completion.zsh.inc ]; then . ${HOME}/.gcloud-sdk/completion.zsh.inc; fi
