#!/bin/bash

export GOPATH=$HOME
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/src

PATH=$GOPATH/bin:$GOROOT/bin:$PATH  # Add go-related stuff to path
PATH=~/.local/bin:$PATH  # Fix for pip on ubuntu, prioritizes local modules.
PATH=$PATH:~/bin  # Add user binaries.

if hash yarn 2>/dev/null; then
    PATH="$(yarn global bin):$PATH"  # Source yarn global path if yarn is installed.
fi

# Rust-related setup
if [ -d "$HOME/.cargo" ]; then
	export PATH="$HOME/.cargo/bin:$PATH"

	if [ -d "$HOME/.cargo/env" ]; then
		source $HOME/.cargo/env
	fi
fi
