#!/bin/zsh

# Tool configuration & initialization.

# Go Jump
eval "$(jump shell)"

# Exports for configuration.
export PURPOSED_OWNER=dalloriam  # For purposed-branded tooling.
export PROJECT_HOME=$HOME/src    # Not _certain_ why... TODO: Investigate.
