#!/bin/zsh
# Much of the magic from https://github.com/jessfraz/dotfiles

# -----------------
# Environment setup
# -----------------
export CLICOLOR=1
export ZSH=$HOME/.oh-my-zsh

# ------------------
# Zsh Initialization
# ------------------
ZSH_THEME="robbyrussell"

plugins=(
    docker
    mercurial
)
source $ZSH/oh-my-zsh.sh


# ---------------------------
# Source all defined dotfiles
# ---------------------------
if [ "$(uname)" = "Darwin" ]; then
    # Do Mac-specific stuff
    source /usr/local/bin/virtualenvwrapper.sh
	if [[ -f "$HOME/.osx" ]]; then
		source ~/.osx
	fi
else
    # Do linux-specific stuff
    source $HOME/.local/bin/virtualenvwrapper.sh
	if [[ -f "$HOME/.linux" ]]; then
		source ~/.linux
	fi
fi
for file in ~/.{prompt,aliases,functions,path,dockerfunc,extra,tools}; do
	if [[ -r "$file" ]] && [[ -f "$file" ]]; then
		source "$file"
	fi
done
unset file
