#!/bin/zsh
# Much of the magic from https://github.com/jessfraz/dotfiles

# -----------------
# Environment setup
# -----------------
export WORKON_HOME=$HOME/.virtualenvs
export CLICOLOR=1
export ZSH=$HOME/.oh-my-zsh

# ------------------
# Zsh Initialization
# ------------------
ZSH_THEME="robbyrussell"

plugins=(
    docker
    mercurial
)
source $ZSH/oh-my-zsh.sh


# ---------------------------
# Source all defined dotfiles
# ---------------------------
if [ "$(uname)" = "Darwin" ]; then
    # Do Mac-specific stuff
    source /usr/local/bin/virtualenvwrapper.sh
	if [[ -f "$HOME/.osx" ]]; then
		source ~/.osx
	fi
else
    # Do linux-specific stuff
    source $HOME/.local/bin/virtualenvwrapper.sh
	if [[ -f "$HOME/.linux" ]]; then
		source ~/.linux
	fi
fi
for file in ~/.{prompt,aliases,functions,path,dockerfunc,extra,exports}; do
	if [[ -r "$file" ]] && [[ -f "$file" ]]; then
		source "$file"
	fi
done
unset file

# ----------------------------
# Initialize some misc. stuff.
# ----------------------------
eval "$(jump shell)"  # Initialize GoJump

# Initialize Google cloud zsh completion
if [ -f ${HOME}/.gcloud-sdk/path.zsh.inc ]; then . ${HOME}/.gcloud-sdk/path.zsh.inc; fi
if [ -f ${HOME}/.gcloud-sdk/completion.zsh.inc ]; then . ${HOME}/.gcloud-sdk/completion.zsh.inc; fi

if hash pyenv 2>/dev/null; then
	eval "$(pyenv init -)"  # Initialize pyenv if it is installed
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/wduss/.google-cloud-sdk/path.zsh.inc' ]; then . '/home/wduss/.google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/wduss/.google-cloud-sdk/completion.zsh.inc' ]; then . '/home/wduss/.google-cloud-sdk/completion.zsh.inc'; fi
