#! /usr/bin/env fish
source "strap/lib.fish"

if is_ubuntu
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
    echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
    sudo apt update && sudo apt -y install gum
else if is_mac
    brew install gum
else if is_arch
    sudo pacman -S --noconfirm gum
end
