#!/usr/bin/env fish

source "strap/lib.fish"

if is_ubuntu
    sudo apt install -y curl \
        gnupg ca-certificates git \
        gcc-multilib g++-multilib cmake libssl-dev pkg-config \
        libfreetype6-dev libasound2-dev libexpat1-dev libxcb-composite0-dev \
        libbz2-dev libsndio-dev freeglut3-dev libxmu-dev libxi-dev libfontconfig1-dev \
        libxcursor-dev

    ensure_installed cargo
    cargo install --git https://github.com/neovide/neovide
end
