#!/usr/bin/env fish
source "strap/lib.fish"

if is_arch
    sudo pacman -S nushell
else if is_ubuntu
    wget -qO- https://apt.fury.io/nushell/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/fury-nushell.gpg
    echo "deb [signed-by=/etc/apt/keyrings/fury-nushell.gpg] https://apt.fury.io/nushell/ /" | sudo tee /etc/apt/sources.list.d/fury-nushell.list
    sudo apt update
    sudo apt install -y nushell
else
    brew install nushell
end
