#! /usr/bin/env fish
source "strap/lib.fish"

if is_ubuntu
    sudo add-apt-repository ppa:neovim-ppa/stable
    sudo apt-get update
    sudo apt-get install neovim -y
else if is_mac
    brew install neovim
end
