#!/usr/bin/env fish
if not type -q clang
    if type -q pacman
        echo "installing clang"
        sudo pacman --noconfirm -S clang
    else
        "no supported platform found for clang"
    end
else
    echo "clang already installed"
end
