name: "Docker"

on:
  push:
    branches:
      - master

jobs:
  Docker-Arch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build devcontainer image
        run: |
          docker build . --tag ghcr.io/dalloriam/dotfiles/arch:latest
          docker push ghcr.io/dalloriam/dotfiles/arch:latest
