steps:
  - uses: actions/checkout@v1.0
    name: Check out code

  - uses: mr-smithers-excellent/docker-build-push@v3
    with:
      image: dalloriam/dotfiles/devenv-base
      registry: docker.pkg.github.com
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
