name: "Docker"

on:
  push: {}

jobs:
  DevEnv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: dotfiles/devenv-base
          registry: docker.pkg.github.com
          tag: latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
